name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    outputs:
      commit_messages: ${{ steps.get_messages.outputs.commit_messages }}  # ðŸ‘ˆ Ð·Ð´ÐµÑÑŒ Ð·Ð°Ð´Ð°Ñ‘Ð¼ output
    steps:
      - uses: actions/checkout@v4

      - name: Extract commit messages
        id: get_messages
        run: |
          echo "commit_messages=${{ toJson(github.event.commits.*.message) }}" >> "$GITHUB_OUTPUT"

  tag_release:
    needs: a_test_job
    if: ${{ github.event_name == 'push' && !contains(needs.a_test_job.outputs.commit_messages, '#skip') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
